-- Use the created database
use car_dealership;

select * from cars;
select * from sales;
select * from salespersons;

-- Q1. What are the details of all cars purchased in the year 2022?

select s.car_id, count(s.car_id) as total_number_of_cars,
 make, type, style, cost_$, sum(cost_$) as total_$
from sales as s
join cars as c
on c.car_id = s.car_id
where year(purchase_date) = '2022'
group by s.car_id;

-- Q2. What is the total number of cars sold by each salesperson?

select sp.salesman_id, name, count(car_id) as number_of_cars_sold
from sales as s
join salespersons as sp
on sp.salesman_id = s.salesman_id
group by sp.salesman_id
order by sp.salesman_id;

-- Q3. What is the total revenue generated by each salesperson?

select s.salesman_id, name, sum(cost_$) as revenue
from sales as s
join cars as c using (car_id) 
join salespersons as sp using (salesman_id )
group by s.salesman_id, name
order by s.salesman_id;

-- Q4. What are the details of the cars sold by each salesperson?

select s.salesman_id, name, s.car_id, count(s.car_id) as number_of_cars,
 make, type, style, sum(cost_$) as price
from sales as s
join cars as c using (car_id)
join salespersons using (salesman_id )
group by s.salesman_id, s.car_id;

-- Q5. What is the total revenue generated by each car type?

select s.car_id, type, sum(cost_$) as revenue
from sales s
join cars as c using (car_id)
group by s.car_id
order by s.car_id ;

-- Q6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?

select s.salesman_id, name, s.car_id, make, type, style, cost_$
from sales as s
join cars as c using (car_id)
join salespersons as sp using (salesman_id )
where name = 'Emily Wong' and year(purchase_date) = '2021';

-- Q7. What is the total revenue generated by the sales of hatchback cars?

select style, sum(cost_$) as revenue
from sales as s
join cars as c using (car_id )
where style = 'Hatchback'
group by style;

-- Q8. What is the total revenue generated by the sales of SUV cars in the year 2022?

select style, sum(cost_$) as revenue
from sales as s
join cars as c using(car_id) 
where style = 'SUV' and year(purchase_date) = '2022'
group by style;

-- Q9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?

select s.salesman_id, name, city, count(s.car_id) number_of_cars
from sales as s
join salespersons as sp using(salesman_id)
where year(purchase_date) = '2023'
group by s.salesman_id
order by count(s.car_id) desc;

-- Q10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?

select s.salesman_id, name, age, sum(cost_$) as revenue
from sales as s
join salespersons  as sp using(salesman_id)
join cars as c using (car_id )
where year(purchase_date) = '2022'
group by s.salesman_id
order by sum(cost_$) desc
limit 1;
